### PR TITLE
Start PR builds

### PR DESCRIPTION
**Pull request by ivirshup**
Trying to setup PR builds through netlify

### CODE REVIEW

**Comment by ivirshup** [comment]
@grst 

* should we turn off all the netlify checks?
* Do you understand why the ["deploy to netlify"](https://github.com/scverse/scverse.github.io/actions/runs/3235490877/jobs/5299994300) step isn't seeing the repository secrets?

**Comment by grst** [comment]
> should we turn off all the netlify checks?

First time I see them, seems they were introduced in a recent version of the action. I don't think we need them! 

> Do you understand why the ["deploy to netlify"](https://github.com/scverse/scverse.github.io/actions/runs/3235490877/jobs/5299994300) step isn't seeing the repository secrets?

This is because you are working on a fork!

**Comment by ivirshup** [comment]
> First time I see them, seems they were introduced in a recent version of the action.

I think it was from me setting up the site?

> This is because you are working on a fork!

Ahh, that makes sense. Are we only going to get previews for PRs made from branches of this repo then?

**Comment by ivirshup** [comment]
@grst I got the deploy working with the netlify github app. 

If that is going to work – but only branches off this PR are going to get builds – I'd say we use the netlify github app tooling.

**Comment by ivirshup** [comment]
So, if you wanted to try the github actions thing, that'd be great. Otherwise I'd close this and go with the github app.

**Comment by grst** [comment]
Let's go with the github app for now. At the moment I have too many things ongoing, but sooner or later I'll need the two-step appraoch for one or the other repo (e.g. preview of the cookiecutter template has the same limitations).

**Comment by ivirshup** [comment]
Cool. I'm going to make a quick dummy PR to make sure this is working, and if so I will close this

**Comment by grst** [comment]
How does the netlify app even work? I mean, how does it know to
 * wait until the build finished and
 * which files to upload?

Or does `hugo` itself run within the netlify app?

**Comment by ivirshup** [comment]
It runs `hugo` itself

**Pull request closed without merging**
